version: '3'

services:

    mongo:
        image: mongo
        container_name: mymongo
        restart: always
    web:
        build: .
        ports:
            - "8000:5000"
        volumes:
            - "./app:/home/kv_store/app"
